openapi: 3.0.0
info:
  title: 'Payment Processing API'
  version: '1.0'
paths:
  /api/ApiDefinitionGenerator:
    get:
      responses:
        '200':
          description: 'Generates an OpenAPI definition file in a yaml format'
  /api/PaymentProcessing/:
    post:
      operationId: 229f369c95b094703348176a4ef409f6
      responses:
        '200':
          description: 'An example resource'
        '401':
          description: 'Unauthorized call to payment processing'
